common:
    version: "0.1"
    server:
        host: "localhost"
        port: 5000
    log:
        conf: "logging_dev.yaml"
    mm_division:
        file_path: "/../../data/mm_division/division.json"
postgres:
    url: "postgresql://"
    host: "localhost"
    port: 5432
    user: "thingaha"
    password: "thingaha"
    db: "thingaha_test"
